# Generated by Django 2.2 on 2020-10-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20201025_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='date',
        ),
    ]
